'''
Created on Aug 27, 2014

@author: ayan

.. module:: base_sql
    :platform: Unix, Windows, MacOS
    :synopsis: SQL for database queries
'''


SITE_INFO = (
             "SELECT ST.DEPTH, ST.LATITUDE, ST.LONGITUDE, ST.SHORT_NAME, ST.STATION_NAME, ST.STATION_NO, ST.NWIS_STATION_NO, ST.DEC_LONGITUDE, ST.DEC_LATITUDE "
             "FROM WEBBDBA.SITE ST "
             "ORDER BY ST.STATION_NAME ASC"
             )


PIEZO_SITES = (
               "SELECT C.FLAGTIC, C.FLAGTOC, C.FLAGUVA_254, C.FLAGUVA_280, FD.FLDCOND, FD.FLDPH, FD.O2, SMP.RECORD_NUMBER, SMP.SAMPLE_DATE, STE.STATION_NAME, SMP.STATION_NO, C.TIC, C.TOC, C.UVA_254, C.UVA_280, FD.WTEMP, STE.NWIS_STATION_NO "
               "FROM WEBBDBA.CARBON C, WEBBDBA.FIELD FD, WEBBDBA.SAMPLE SMP, WEBBDBA.SITE STE "
               "WHERE ( ( SMP.RECORD_NUMBER = C.RECORD_NUMBER(+) ) AND ( SMP.RECORD_NUMBER = FD.RECORD_NUMBER ) AND ( STE.STATION_NO = SMP.STATION_NO ) ) AND ( STE.SITE_GROUP_CD IN ({groups}) ) AND ( SMP.SAMPLE_DATE >= :StartDate ) AND ( SMP.SAMPLE_DATE <= :EndDate ) "
               "ORDER BY SMP.SAMPLE_DATE ASC, SMP.STATION_NO ASC"
               )


WELL_CK_VALUES = (
                  "SELECT 0.3048*WHM.NGVD_WS_ELEV AS NGVD_WS_ELEV, WHM.MEAS_DATE, WHM.DEPTH_TO_WS, WHM.WS_ELEV, WHMP.STATION_NO, WHMP.LOCAL_MP_ELEV, WHMP.NGVD_MP_ELEV, VWS.SHORT_NAME "
                  "FROM WEBBDBA.WELL_HEAD_MEAS WHM, WEBBDBA.WELL_HEAD_MP WHMP, WEBBDBA.VW_WISKI_SITES VWS "
                  "WHERE ( ( VWS.STATION_NO = WHM.STATION_NO ) AND ( VWS.STATION_NO = WHMP.STATION_NO ) ) AND ( VWS.SHORT_NAME IN ({sites}) ) AND ( WHM.MEAS_DATE <= :EndDT ) AND ( WHM.MEAS_DATE >= :StartDT )"
                  "ORDER BY WHM.MEAS_DATE ASC"
                  )


DATA_WITH_UV = (
                "SELECT ANN.ALKALINITY, SMP.RECORD_NUMBER, SMP.SAMPLE_DATE, STE.SHORT_NAME, STE.STATION_NO "
                "FROM WEBBDBA.ANION ANN, WEBBDBA.SAMPLE SMP, WEBBDBA.SITE STE "
                "WHERE ( ( SMP.RECORD_NUMBER = ANN.RECORD_NUMBER(+) ) AND ( STE.STATION_NO = SMP.STATION_NO ) ) AND ( STE.SITE_GROUP_CD IN ({groups}) ) AND ( SMP.SAMPLE_DATE >= :StartDate ) AND ( SMP.SAMPLE_DATE <= :EndDate ) "
                "ORDER BY STE.SHORT_NAME ASC, ANN.ALKALINITY ASC"
                )


WITH_DATA = (
             "SELECT FLD.FLDCOND, FLD.FLDPH, SMP.RECORD_NUMBER, SMP.SAMPLE_DATE, STE.SHORT_NAME, STE.STATION_NO, CAR.TOC, FLD.WTEMP "
             "FROM WEBBDBA.CARBON CAR, WEBBDBA.FIELD FLD, WEBBDBA.SAMPLE SMP, WEBBDBA.SITE STE "
             "WHERE ( ( SMP.RECORD_NUMBER = CAR.RECORD_NUMBER(+) ) AND ( SMP.RECORD_NUMBER = FLD.RECORD_NUMBER ) AND ( STE.STATION_NO = SMP.STATION_NO ) ) AND ( STE.SITE_GROUP_CD IN ({groups}) ) AND ( SMP.SAMPLE_DATE >= :StartDate ) AND ( SMP.SAMPLE_DATE <= :EndDate ) "
             "ORDER BY SMP.RECORD_NUMBER ASC"
             )


WELL_UVS = (
            "SELECT VR.EDITED_VALUE AS DEPTH_ABOVE_SENSOR, VR.RESULT_DATETIME "
            "FROM WEBBDBA.UV_RESULTS VR, WEBBDBA.VW_WISKI_SITES VWS "
            "WHERE ( ( VWS.STATION_NO = VR.STATION_NO ) ) AND ( VWS.SHORT_NAME IN ({sites}) ) AND ( VR.RESULT_DATETIME <= :EndUVDate ) AND ( VR.RESULT_DATETIME >= :StartUVDate ) AND ( VR.PARAMETER_CODE IN (( '72019' )) )"
            )


WELL_DATUMS = (
               "SELECT STE.DEPTH, STE.SHORT_NAME, STE.STATION_NO, WMP.LOCAL_MP_ELEV, WMP.NGVD_MP_ELEV "
               "FROM WEBBDBA.SITE STE, WEBBDBA.WELL_HEAD_MP WMP "
               "WHERE ( ( STE.STATION_NO = WMP.STATION_NO ) ) AND ( WMP.MP_VALID = 'Y' )"
               )